version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: boeing_chatbot_db
    environment:
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: chatbot_password
      POSTGRES_DB: boeing_chatbot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatbot_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  chatbot:
    build: .
    container_name: boeing_chatbot_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URI: postgresql://chatbot_user:chatbot_password@postgres:5432/boeing_chatbot
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./chroma_db:/app/chroma_db
    restart: unless-stopped

volumes:
  postgres_data:
